// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package pgstore

import (
	"context"
)

// iteratorForAppendGameEvents implements pgx.CopyFromSource.
type iteratorForAppendGameEvents struct {
	rows                 []AppendGameEventsParams
	skippedFirstNextCall bool
}

func (r *iteratorForAppendGameEvents) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForAppendGameEvents) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].GameID,
		r.rows[0].Sequence,
		r.rows[0].EventType,
		r.rows[0].Payload,
		r.rows[0].Envelope,
		r.rows[0].CausedByCommandID,
		r.rows[0].HandID,
		r.rows[0].StateVersionAfter,
		r.rows[0].OccurredAt,
	}, nil
}

func (r iteratorForAppendGameEvents) Err() error {
	return nil
}

// Bulk variant for when a single command produces multiple events.
// Uses pgx's COPY FROM for speed. Atomicity is guaranteed by wrapping in a transaction.
func (q *Queries) AppendGameEvents(ctx context.Context, arg []AppendGameEventsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"game_events"}, []string{"game_id", "sequence", "event_type", "payload", "envelope", "caused_by_command_id", "hand_id", "state_version_after", "occurred_at"}, &iteratorForAppendGameEvents{rows: arg})
}
