// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: game_snapshots.sql

package pgstore

import (
	"context"

	uuid "github.com/google/uuid"
)

const createSnapshot = `-- name: CreateSnapshot :one
INSERT INTO game_snapshots (game_id, sequence, hand_number, state_proto)
VALUES ($1, $2, $3, $4)
RETURNING id, game_id, sequence, hand_number, state_proto, taken_at
`

type CreateSnapshotParams struct {
	GameID     uuid.UUID
	Sequence   int64
	HandNumber int64
	StateProto []byte
}

func (q *Queries) CreateSnapshot(ctx context.Context, arg CreateSnapshotParams) (GameSnapshot, error) {
	row := q.db.QueryRow(ctx, createSnapshot,
		arg.GameID,
		arg.Sequence,
		arg.HandNumber,
		arg.StateProto,
	)
	var i GameSnapshot
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.Sequence,
		&i.HandNumber,
		&i.StateProto,
		&i.TakenAt,
	)
	return i, err
}

const deleteSnapshotsBefore = `-- name: DeleteSnapshotsBefore :exec
DELETE FROM game_snapshots
WHERE game_id = $1 AND sequence < $2
`

type DeleteSnapshotsBeforeParams struct {
	GameID   uuid.UUID
	Sequence int64
}

// Snapshot pruning. Keep N most recent snapshots per game.
func (q *Queries) DeleteSnapshotsBefore(ctx context.Context, arg DeleteSnapshotsBeforeParams) error {
	_, err := q.db.Exec(ctx, deleteSnapshotsBefore, arg.GameID, arg.Sequence)
	return err
}

const getLatestSnapshot = `-- name: GetLatestSnapshot :one
SELECT id, game_id, sequence, hand_number, state_proto, taken_at FROM game_snapshots
WHERE game_id = $1
ORDER BY sequence DESC
LIMIT 1
`

func (q *Queries) GetLatestSnapshot(ctx context.Context, gameID uuid.UUID) (GameSnapshot, error) {
	row := q.db.QueryRow(ctx, getLatestSnapshot, gameID)
	var i GameSnapshot
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.Sequence,
		&i.HandNumber,
		&i.StateProto,
		&i.TakenAt,
	)
	return i, err
}

const getSnapshotAtOrBefore = `-- name: GetSnapshotAtOrBefore :one
SELECT id, game_id, sequence, hand_number, state_proto, taken_at FROM game_snapshots
WHERE game_id = $1 AND sequence <= $2
ORDER BY sequence DESC
LIMIT 1
`

type GetSnapshotAtOrBeforeParams struct {
	GameID   uuid.UUID
	Sequence int64
}

// For replay: find the most recent snapshot at or before a target sequence.
func (q *Queries) GetSnapshotAtOrBefore(ctx context.Context, arg GetSnapshotAtOrBeforeParams) (GameSnapshot, error) {
	row := q.db.QueryRow(ctx, getSnapshotAtOrBefore, arg.GameID, arg.Sequence)
	var i GameSnapshot
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.Sequence,
		&i.HandNumber,
		&i.StateProto,
		&i.TakenAt,
	)
	return i, err
}
