// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: game_configs.sql

package pgstore

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countSearchGameConfigs = `-- name: CountSearchGameConfigs :one
SELECT COUNT(*)::BIGINT AS total
FROM game_configs
WHERE deleted_at IS NULL
  AND ($1::TEXT = ''    OR table_name ILIKE '%' || $1::TEXT || '%')
  AND ($2::BIGINT = 0   OR big_blind  = $2::BIGINT)
  AND ($3::SMALLINT = 0 OR variant    = $3::SMALLINT)
  AND ($4::SMALLINT = 0 OR structure  = $4::SMALLINT)
`

type CountSearchGameConfigsParams struct {
	Column1 string
	Column2 int64
	Column3 int16
	Column4 int16
}

func (q *Queries) CountSearchGameConfigs(ctx context.Context, arg CountSearchGameConfigsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchGameConfigs,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createGameConfig = `-- name: CreateGameConfig :one
INSERT INTO game_configs (
    table_name, variant, structure, currency,
    small_blind, big_blind, min_buy_in, max_buy_in,
    max_seats, is_private, config_proto
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING game_id, table_name, variant, structure, currency, small_blind, big_blind, min_buy_in, max_buy_in, max_seats, is_private, config_proto, created_at, updated_at, deleted_at
`

type CreateGameConfigParams struct {
	TableName   string
	Variant     int16
	Structure   int16
	Currency    string
	SmallBlind  int64
	BigBlind    int64
	MinBuyIn    int64
	MaxBuyIn    int64
	MaxSeats    int16
	IsPrivate   bool
	ConfigProto []byte
}

func (q *Queries) CreateGameConfig(ctx context.Context, arg CreateGameConfigParams) (GameConfig, error) {
	row := q.db.QueryRow(ctx, createGameConfig,
		arg.TableName,
		arg.Variant,
		arg.Structure,
		arg.Currency,
		arg.SmallBlind,
		arg.BigBlind,
		arg.MinBuyIn,
		arg.MaxBuyIn,
		arg.MaxSeats,
		arg.IsPrivate,
		arg.ConfigProto,
	)
	var i GameConfig
	err := row.Scan(
		&i.GameID,
		&i.TableName,
		&i.Variant,
		&i.Structure,
		&i.Currency,
		&i.SmallBlind,
		&i.BigBlind,
		&i.MinBuyIn,
		&i.MaxBuyIn,
		&i.MaxSeats,
		&i.IsPrivate,
		&i.ConfigProto,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getGameConfig = `-- name: GetGameConfig :one
SELECT game_id, table_name, variant, structure, currency, small_blind, big_blind, min_buy_in, max_buy_in, max_seats, is_private, config_proto, created_at, updated_at, deleted_at FROM game_configs WHERE game_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetGameConfig(ctx context.Context, gameID uuid.UUID) (GameConfig, error) {
	row := q.db.QueryRow(ctx, getGameConfig, gameID)
	var i GameConfig
	err := row.Scan(
		&i.GameID,
		&i.TableName,
		&i.Variant,
		&i.Structure,
		&i.Currency,
		&i.SmallBlind,
		&i.BigBlind,
		&i.MinBuyIn,
		&i.MaxBuyIn,
		&i.MaxSeats,
		&i.IsPrivate,
		&i.ConfigProto,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listActiveGameConfigs = `-- name: ListActiveGameConfigs :many
SELECT game_id, table_name, variant, structure, currency, small_blind, big_blind, min_buy_in, max_buy_in, max_seats, is_private, config_proto, created_at, updated_at, deleted_at FROM game_configs
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListActiveGameConfigsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListActiveGameConfigs(ctx context.Context, arg ListActiveGameConfigsParams) ([]GameConfig, error) {
	rows, err := q.db.Query(ctx, listActiveGameConfigs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GameConfig{}
	for rows.Next() {
		var i GameConfig
		if err := rows.Scan(
			&i.GameID,
			&i.TableName,
			&i.Variant,
			&i.Structure,
			&i.Currency,
			&i.SmallBlind,
			&i.BigBlind,
			&i.MinBuyIn,
			&i.MaxBuyIn,
			&i.MaxSeats,
			&i.IsPrivate,
			&i.ConfigProto,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchGameConfigs = `-- name: SearchGameConfigs :many
SELECT
    game_id, table_name, variant, structure, currency,
    small_blind, big_blind, min_buy_in, max_buy_in,
    max_seats, is_private, created_at
FROM game_configs
WHERE deleted_at IS NULL
  AND ($1::TEXT = ''    OR table_name ILIKE '%' || $1::TEXT || '%')
  AND ($2::BIGINT = 0   OR big_blind  = $2::BIGINT)
  AND ($3::SMALLINT = 0 OR variant    = $3::SMALLINT)
  AND ($4::SMALLINT = 0 OR structure  = $4::SMALLINT)
ORDER BY created_at DESC
LIMIT $5 OFFSET $6
`

type SearchGameConfigsParams struct {
	Column1 string
	Column2 int64
	Column3 int16
	Column4 int16
	Limit   int32
	Offset  int32
}

type SearchGameConfigsRow struct {
	GameID     uuid.UUID
	TableName  string
	Variant    int16
	Structure  int16
	Currency   string
	SmallBlind int64
	BigBlind   int64
	MinBuyIn   int64
	MaxBuyIn   int64
	MaxSeats   int16
	IsPrivate  bool
	CreatedAt  pgtype.Timestamptz
}

// Lobby search. All filters are optional and AND-combined.
// Filtering on denormalized columns rather than decoding config_proto.
// Sentinels: name_query=” means no name filter; 0 means no numeric filter.
func (q *Queries) SearchGameConfigs(ctx context.Context, arg SearchGameConfigsParams) ([]SearchGameConfigsRow, error) {
	rows, err := q.db.Query(ctx, searchGameConfigs,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchGameConfigsRow{}
	for rows.Next() {
		var i SearchGameConfigsRow
		if err := rows.Scan(
			&i.GameID,
			&i.TableName,
			&i.Variant,
			&i.Structure,
			&i.Currency,
			&i.SmallBlind,
			&i.BigBlind,
			&i.MinBuyIn,
			&i.MaxBuyIn,
			&i.MaxSeats,
			&i.IsPrivate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteGameConfig = `-- name: SoftDeleteGameConfig :exec
UPDATE game_configs SET deleted_at = NOW(), updated_at = NOW()
WHERE game_id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteGameConfig(ctx context.Context, gameID uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteGameConfig, gameID)
	return err
}
