// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: game_events.sql

package pgstore

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendGameEvent = `-- name: AppendGameEvent :one
INSERT INTO game_events (
    game_id, sequence, event_type, payload, envelope,
    caused_by_command_id, hand_id, state_version_after, occurred_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, game_id, sequence, event_type, payload, envelope, caused_by_command_id, hand_id, state_version_after, occurred_at, inserted_at, published_at
`

type AppendGameEventParams struct {
	GameID            uuid.UUID
	Sequence          int64
	EventType         string
	Payload           []byte
	Envelope          []byte
	CausedByCommandID uuid.NullUUID
	HandID            uuid.NullUUID
	StateVersionAfter int64
	OccurredAt        pgtype.Timestamptz
}

// Inserts a single event. Relies on UNIQUE (game_id, sequence) for OCC.
// Caller catches "unique_violation" (pgerrcode 23505) and retries with refreshed state.
func (q *Queries) AppendGameEvent(ctx context.Context, arg AppendGameEventParams) (GameEvent, error) {
	row := q.db.QueryRow(ctx, appendGameEvent,
		arg.GameID,
		arg.Sequence,
		arg.EventType,
		arg.Payload,
		arg.Envelope,
		arg.CausedByCommandID,
		arg.HandID,
		arg.StateVersionAfter,
		arg.OccurredAt,
	)
	var i GameEvent
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.Sequence,
		&i.EventType,
		&i.Payload,
		&i.Envelope,
		&i.CausedByCommandID,
		&i.HandID,
		&i.StateVersionAfter,
		&i.OccurredAt,
		&i.InsertedAt,
		&i.PublishedAt,
	)
	return i, err
}

type AppendGameEventsParams struct {
	GameID            uuid.UUID
	Sequence          int64
	EventType         string
	Payload           []byte
	Envelope          []byte
	CausedByCommandID uuid.NullUUID
	HandID            uuid.NullUUID
	StateVersionAfter int64
	OccurredAt        pgtype.Timestamptz
}

const findEventByCommandID = `-- name: FindEventByCommandID :one
SELECT id, game_id, sequence, event_type, payload, envelope, caused_by_command_id, hand_id, state_version_after, occurred_at, inserted_at, published_at FROM game_events
WHERE caused_by_command_id = $1
  AND game_id = $2
ORDER BY sequence ASC
LIMIT 1
`

type FindEventByCommandIDParams struct {
	CausedByCommandID uuid.NullUUID
	GameID            uuid.UUID
}

// Idempotency check: was this command already processed for this specific game?
func (q *Queries) FindEventByCommandID(ctx context.Context, arg FindEventByCommandIDParams) (GameEvent, error) {
	row := q.db.QueryRow(ctx, findEventByCommandID, arg.CausedByCommandID, arg.GameID)
	var i GameEvent
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.Sequence,
		&i.EventType,
		&i.Payload,
		&i.Envelope,
		&i.CausedByCommandID,
		&i.HandID,
		&i.StateVersionAfter,
		&i.OccurredAt,
		&i.InsertedAt,
		&i.PublishedAt,
	)
	return i, err
}

const findEventByCommandIDGlobal = `-- name: FindEventByCommandIDGlobal :one
SELECT id, game_id, sequence, event_type, payload, envelope, caused_by_command_id, hand_id, state_version_after, occurred_at, inserted_at, published_at FROM game_events
WHERE caused_by_command_id = $1
ORDER BY sequence ASC
LIMIT 1
`

// Idempotency check for commands that precede game creation (e.g. CreateTable),
// where the game_id is not yet known at idempotency-check time.
func (q *Queries) FindEventByCommandIDGlobal(ctx context.Context, causedByCommandID uuid.NullUUID) (GameEvent, error) {
	row := q.db.QueryRow(ctx, findEventByCommandIDGlobal, causedByCommandID)
	var i GameEvent
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.Sequence,
		&i.EventType,
		&i.Payload,
		&i.Envelope,
		&i.CausedByCommandID,
		&i.HandID,
		&i.StateVersionAfter,
		&i.OccurredAt,
		&i.InsertedAt,
		&i.PublishedAt,
	)
	return i, err
}

const getEventsForGame = `-- name: GetEventsForGame :many
SELECT id, game_id, sequence, event_type, payload, envelope, caused_by_command_id, hand_id, state_version_after, occurred_at, inserted_at, published_at FROM game_events
WHERE game_id = $1 AND sequence >= $2
ORDER BY sequence ASC
LIMIT $3
`

type GetEventsForGameParams struct {
	GameID   uuid.UUID
	Sequence int64
	Limit    int32
}

func (q *Queries) GetEventsForGame(ctx context.Context, arg GetEventsForGameParams) ([]GameEvent, error) {
	rows, err := q.db.Query(ctx, getEventsForGame, arg.GameID, arg.Sequence, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GameEvent{}
	for rows.Next() {
		var i GameEvent
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.Sequence,
			&i.EventType,
			&i.Payload,
			&i.Envelope,
			&i.CausedByCommandID,
			&i.HandID,
			&i.StateVersionAfter,
			&i.OccurredAt,
			&i.InsertedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventsForHand = `-- name: GetEventsForHand :many
SELECT id, game_id, sequence, event_type, payload, envelope, caused_by_command_id, hand_id, state_version_after, occurred_at, inserted_at, published_at FROM game_events
WHERE hand_id = $1
ORDER BY sequence ASC
`

func (q *Queries) GetEventsForHand(ctx context.Context, handID uuid.NullUUID) ([]GameEvent, error) {
	rows, err := q.db.Query(ctx, getEventsForHand, handID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GameEvent{}
	for rows.Next() {
		var i GameEvent
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.Sequence,
			&i.EventType,
			&i.Payload,
			&i.Envelope,
			&i.CausedByCommandID,
			&i.HandID,
			&i.StateVersionAfter,
			&i.OccurredAt,
			&i.InsertedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestSequence = `-- name: GetLatestSequence :one
SELECT COALESCE(MAX(sequence), 0)::BIGINT AS latest_sequence
FROM game_events
WHERE game_id = $1
`

func (q *Queries) GetLatestSequence(ctx context.Context, gameID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getLatestSequence, gameID)
	var latest_sequence int64
	err := row.Scan(&latest_sequence)
	return latest_sequence, err
}

const getUnpublishedEvents = `-- name: GetUnpublishedEvents :many
SELECT id, game_id, sequence, event_type, payload, envelope, caused_by_command_id, hand_id, state_version_after, occurred_at, inserted_at, published_at FROM game_events
WHERE published_at IS NULL
ORDER BY id ASC
LIMIT $1
`

func (q *Queries) GetUnpublishedEvents(ctx context.Context, limit int32) ([]GameEvent, error) {
	rows, err := q.db.Query(ctx, getUnpublishedEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GameEvent{}
	for rows.Next() {
		var i GameEvent
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.Sequence,
			&i.EventType,
			&i.Payload,
			&i.Envelope,
			&i.CausedByCommandID,
			&i.HandID,
			&i.StateVersionAfter,
			&i.OccurredAt,
			&i.InsertedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEventsPublished = `-- name: MarkEventsPublished :exec
UPDATE game_events
SET published_at = NOW()
WHERE id = ANY($1::BIGINT[])
`

func (q *Queries) MarkEventsPublished(ctx context.Context, dollar_1 []int64) error {
	_, err := q.db.Exec(ctx, markEventsPublished, dollar_1)
	return err
}
