// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pgstore

import (
	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type GameConfig struct {
	GameID      uuid.UUID
	TableName   string
	Variant     int16
	Structure   int16
	Currency    string
	SmallBlind  int64
	BigBlind    int64
	MinBuyIn    int64
	MaxBuyIn    int64
	MaxSeats    int16
	IsPrivate   bool
	ConfigProto []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type GameEvent struct {
	ID                int64
	GameID            uuid.UUID
	Sequence          int64
	EventType         string
	Payload           []byte
	Envelope          []byte
	CausedByCommandID uuid.NullUUID
	HandID            uuid.NullUUID
	StateVersionAfter int64
	OccurredAt        pgtype.Timestamptz
	InsertedAt        pgtype.Timestamptz
	PublishedAt       pgtype.Timestamptz
}

type GameSnapshot struct {
	ID         int64
	GameID     uuid.UUID
	Sequence   int64
	HandNumber int64
	StateProto []byte
	TakenAt    pgtype.Timestamptz
}

type StepDepositReport struct {
	ID            int64
	UserID        uuid.UUID
	ReportID      uuid.UUID
	ReportedSteps int64
	CreditedChips int64
	LocalDate     pgtype.Date
	ReportedAt    pgtype.Timestamptz
	Reason        string
}

type User struct {
	ID              uuid.UUID
	DisplayName     string
	ExternalID      *string
	Timezone        string
	MaxDailyDeposit int64
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
}

type UserDailyStep struct {
	UserID         uuid.UUID
	LocalDate      pgtype.Date
	MaxSteps       int64
	LastReportedAt pgtype.Timestamptz
}

type UserSnapshot struct {
	UserID         uuid.UUID
	ChipBalance    int64
	TotalDeposited int64
	TotalReports   int64
	LastDepositAt  pgtype.Timestamptz
	LastActivityAt pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}
