// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pgstore

import (
	"context"

	uuid "github.com/google/uuid"
)

type Querier interface {
	// Inserts a single event. Relies on UNIQUE (game_id, sequence) for OCC.
	// Caller catches "unique_violation" (pgerrcode 23505) and retries with refreshed state.
	AppendGameEvent(ctx context.Context, arg AppendGameEventParams) (GameEvent, error)
	// Bulk variant for when a single command produces multiple events.
	// Uses pgx's COPY FROM for speed. Atomicity is guaranteed by wrapping in a transaction.
	AppendGameEvents(ctx context.Context, arg []AppendGameEventsParams) (int64, error)
	CountSearchGameConfigs(ctx context.Context, arg CountSearchGameConfigsParams) (int64, error)
	CreateGameConfig(ctx context.Context, arg CreateGameConfigParams) (GameConfig, error)
	CreateSnapshot(ctx context.Context, arg CreateSnapshotParams) (GameSnapshot, error)
	// Snapshot pruning. Keep N most recent snapshots per game.
	DeleteSnapshotsBefore(ctx context.Context, arg DeleteSnapshotsBeforeParams) error
	// Idempotency check: was this command already processed?
	FindEventByCommandID(ctx context.Context, causedByCommandID uuid.NullUUID) (GameEvent, error)
	GetEventsForGame(ctx context.Context, arg GetEventsForGameParams) ([]GameEvent, error)
	GetEventsForHand(ctx context.Context, handID uuid.NullUUID) ([]GameEvent, error)
	GetGameConfig(ctx context.Context, gameID uuid.UUID) (GameConfig, error)
	GetLatestSequence(ctx context.Context, gameID uuid.UUID) (int64, error)
	GetLatestSnapshot(ctx context.Context, gameID uuid.UUID) (GameSnapshot, error)
	// For replay: find the most recent snapshot at or before a target sequence.
	GetSnapshotAtOrBefore(ctx context.Context, arg GetSnapshotAtOrBeforeParams) (GameSnapshot, error)
	GetUnpublishedEvents(ctx context.Context, limit int32) ([]GameEvent, error)
	ListActiveGameConfigs(ctx context.Context, arg ListActiveGameConfigsParams) ([]GameConfig, error)
	MarkEventsPublished(ctx context.Context, dollar_1 []int64) error
	// Lobby search. All filters are optional and AND-combined.
	// Filtering on denormalized columns rather than decoding config_proto.
	// Sentinels: name_query='' means no name filter; 0 means no numeric filter.
	SearchGameConfigs(ctx context.Context, arg SearchGameConfigsParams) ([]SearchGameConfigsRow, error)
	SoftDeleteGameConfig(ctx context.Context, gameID uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
