// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: step_deposits.sql

package pgstore

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countDepositReports = `-- name: CountDepositReports :one
SELECT COUNT(*)::BIGINT FROM step_deposit_reports WHERE user_id = $1
`

func (q *Queries) CountDepositReports(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDepositReports, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const findDepositReportByReportID = `-- name: FindDepositReportByReportID :one
SELECT id, user_id, report_id, reported_steps, credited_chips, local_date, reported_at, reason FROM step_deposit_reports
WHERE user_id = $1 AND report_id = $2
`

type FindDepositReportByReportIDParams struct {
	UserID   uuid.UUID
	ReportID uuid.UUID
}

func (q *Queries) FindDepositReportByReportID(ctx context.Context, arg FindDepositReportByReportIDParams) (StepDepositReport, error) {
	row := q.db.QueryRow(ctx, findDepositReportByReportID, arg.UserID, arg.ReportID)
	var i StepDepositReport
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ReportID,
		&i.ReportedSteps,
		&i.CreditedChips,
		&i.LocalDate,
		&i.ReportedAt,
		&i.Reason,
	)
	return i, err
}

const getDailyStepsForUpdate = `-- name: GetDailyStepsForUpdate :one
SELECT user_id, local_date, max_steps, last_reported_at FROM user_daily_steps
WHERE user_id = $1 AND local_date = $2
FOR UPDATE
`

type GetDailyStepsForUpdateParams struct {
	UserID    uuid.UUID
	LocalDate pgtype.Date
}

// Row-level lock for the deposit transaction.
func (q *Queries) GetDailyStepsForUpdate(ctx context.Context, arg GetDailyStepsForUpdateParams) (UserDailyStep, error) {
	row := q.db.QueryRow(ctx, getDailyStepsForUpdate, arg.UserID, arg.LocalDate)
	var i UserDailyStep
	err := row.Scan(
		&i.UserID,
		&i.LocalDate,
		&i.MaxSteps,
		&i.LastReportedAt,
	)
	return i, err
}

const insertDepositReport = `-- name: InsertDepositReport :one
INSERT INTO step_deposit_reports (user_id, report_id, reported_steps, credited_chips, local_date, reason)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id, report_id) DO NOTHING
RETURNING id, user_id, report_id, reported_steps, credited_chips, local_date, reported_at, reason
`

type InsertDepositReportParams struct {
	UserID        uuid.UUID
	ReportID      uuid.UUID
	ReportedSteps int64
	CreditedChips int64
	LocalDate     pgtype.Date
	Reason        string
}

// Records the audit row. Returns the inserted row; on conflict (duplicate
// report_id) the DO NOTHING clause fires and nothing is returned.
func (q *Queries) InsertDepositReport(ctx context.Context, arg InsertDepositReportParams) (StepDepositReport, error) {
	row := q.db.QueryRow(ctx, insertDepositReport,
		arg.UserID,
		arg.ReportID,
		arg.ReportedSteps,
		arg.CreditedChips,
		arg.LocalDate,
		arg.Reason,
	)
	var i StepDepositReport
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ReportID,
		&i.ReportedSteps,
		&i.CreditedChips,
		&i.LocalDate,
		&i.ReportedAt,
		&i.Reason,
	)
	return i, err
}

const listDepositReports = `-- name: ListDepositReports :many
SELECT id, user_id, report_id, reported_steps, credited_chips, local_date, reported_at, reason FROM step_deposit_reports
WHERE user_id = $1
ORDER BY reported_at DESC
LIMIT $2 OFFSET $3
`

type ListDepositReportsParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListDepositReports(ctx context.Context, arg ListDepositReportsParams) ([]StepDepositReport, error) {
	rows, err := q.db.Query(ctx, listDepositReports, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StepDepositReport{}
	for rows.Next() {
		var i StepDepositReport
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ReportID,
			&i.ReportedSteps,
			&i.CreditedChips,
			&i.LocalDate,
			&i.ReportedAt,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumCreditedToday = `-- name: SumCreditedToday :one
SELECT COALESCE(SUM(credited_chips), 0)::BIGINT
FROM step_deposit_reports
WHERE user_id = $1 AND local_date = $2
`

type SumCreditedTodayParams struct {
	UserID    uuid.UUID
	LocalDate pgtype.Date
}

func (q *Queries) SumCreditedToday(ctx context.Context, arg SumCreditedTodayParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumCreditedToday, arg.UserID, arg.LocalDate)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const upsertDailyStepsHighWaterMark = `-- name: UpsertDailyStepsHighWaterMark :one
INSERT INTO user_daily_steps (user_id, local_date, max_steps, last_reported_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (user_id, local_date) DO UPDATE
    SET max_steps        = GREATEST(user_daily_steps.max_steps, EXCLUDED.max_steps),
        last_reported_at = CASE
            WHEN EXCLUDED.max_steps > user_daily_steps.max_steps THEN NOW()
            ELSE user_daily_steps.last_reported_at
        END
RETURNING user_id, local_date, max_steps, last_reported_at
`

type UpsertDailyStepsHighWaterMarkParams struct {
	UserID    uuid.UUID
	LocalDate pgtype.Date
	MaxSteps  int64
}

// Atomically update only if the new value is higher.
func (q *Queries) UpsertDailyStepsHighWaterMark(ctx context.Context, arg UpsertDailyStepsHighWaterMarkParams) (UserDailyStep, error) {
	row := q.db.QueryRow(ctx, upsertDailyStepsHighWaterMark, arg.UserID, arg.LocalDate, arg.MaxSteps)
	var i UserDailyStep
	err := row.Scan(
		&i.UserID,
		&i.LocalDate,
		&i.MaxSteps,
		&i.LastReportedAt,
	)
	return i, err
}
