// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_snapshots.sql

package pgstore

import (
	"context"

	uuid "github.com/google/uuid"
)

const applyDepositToSnapshot = `-- name: ApplyDepositToSnapshot :one
UPDATE user_snapshots
SET
    chip_balance     = chip_balance + $2,
    total_deposited  = total_deposited + $2,
    total_reports    = total_reports + 1,
    last_deposit_at  = CASE WHEN $2 > 0 THEN NOW() ELSE last_deposit_at END,
    last_activity_at = NOW(),
    updated_at       = NOW()
WHERE user_id = $1
RETURNING user_id, chip_balance, total_deposited, total_reports, last_deposit_at, last_activity_at, updated_at
`

type ApplyDepositToSnapshotParams struct {
	UserID      uuid.UUID
	ChipBalance int64
}

func (q *Queries) ApplyDepositToSnapshot(ctx context.Context, arg ApplyDepositToSnapshotParams) (UserSnapshot, error) {
	row := q.db.QueryRow(ctx, applyDepositToSnapshot, arg.UserID, arg.ChipBalance)
	var i UserSnapshot
	err := row.Scan(
		&i.UserID,
		&i.ChipBalance,
		&i.TotalDeposited,
		&i.TotalReports,
		&i.LastDepositAt,
		&i.LastActivityAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserSnapshot = `-- name: CreateUserSnapshot :one
INSERT INTO user_snapshots (user_id)
VALUES ($1)
RETURNING user_id, chip_balance, total_deposited, total_reports, last_deposit_at, last_activity_at, updated_at
`

func (q *Queries) CreateUserSnapshot(ctx context.Context, userID uuid.UUID) (UserSnapshot, error) {
	row := q.db.QueryRow(ctx, createUserSnapshot, userID)
	var i UserSnapshot
	err := row.Scan(
		&i.UserID,
		&i.ChipBalance,
		&i.TotalDeposited,
		&i.TotalReports,
		&i.LastDepositAt,
		&i.LastActivityAt,
		&i.UpdatedAt,
	)
	return i, err
}

const creditUserBalance = `-- name: CreditUserBalance :one
UPDATE user_snapshots
SET
    chip_balance     = chip_balance + $2,
    last_activity_at = NOW(),
    updated_at       = NOW()
WHERE user_id = $1
RETURNING user_id, chip_balance, total_deposited, total_reports, last_deposit_at, last_activity_at, updated_at
`

type CreditUserBalanceParams struct {
	UserID      uuid.UUID
	ChipBalance int64
}

// For cash-out (returning chips when a user leaves a table).
func (q *Queries) CreditUserBalance(ctx context.Context, arg CreditUserBalanceParams) (UserSnapshot, error) {
	row := q.db.QueryRow(ctx, creditUserBalance, arg.UserID, arg.ChipBalance)
	var i UserSnapshot
	err := row.Scan(
		&i.UserID,
		&i.ChipBalance,
		&i.TotalDeposited,
		&i.TotalReports,
		&i.LastDepositAt,
		&i.LastActivityAt,
		&i.UpdatedAt,
	)
	return i, err
}

const debitUserBalance = `-- name: DebitUserBalance :one
UPDATE user_snapshots
SET
    chip_balance     = chip_balance - $2,
    last_activity_at = NOW(),
    updated_at       = NOW()
WHERE user_id = $1 AND chip_balance >= $2
RETURNING user_id, chip_balance, total_deposited, total_reports, last_deposit_at, last_activity_at, updated_at
`

type DebitUserBalanceParams struct {
	UserID      uuid.UUID
	ChipBalance int64
}

// For buy-ins when a user joins a table. Atomic insufficient-funds check:
// if balance < amount the WHERE clause matches nothing and ErrNoRows is returned.
func (q *Queries) DebitUserBalance(ctx context.Context, arg DebitUserBalanceParams) (UserSnapshot, error) {
	row := q.db.QueryRow(ctx, debitUserBalance, arg.UserID, arg.ChipBalance)
	var i UserSnapshot
	err := row.Scan(
		&i.UserID,
		&i.ChipBalance,
		&i.TotalDeposited,
		&i.TotalReports,
		&i.LastDepositAt,
		&i.LastActivityAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserSnapshot = `-- name: GetUserSnapshot :one
SELECT user_id, chip_balance, total_deposited, total_reports, last_deposit_at, last_activity_at, updated_at FROM user_snapshots WHERE user_id = $1
`

func (q *Queries) GetUserSnapshot(ctx context.Context, userID uuid.UUID) (UserSnapshot, error) {
	row := q.db.QueryRow(ctx, getUserSnapshot, userID)
	var i UserSnapshot
	err := row.Scan(
		&i.UserID,
		&i.ChipBalance,
		&i.TotalDeposited,
		&i.TotalReports,
		&i.LastDepositAt,
		&i.LastActivityAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserSnapshotForUpdate = `-- name: GetUserSnapshotForUpdate :one
SELECT user_id, chip_balance, total_deposited, total_reports, last_deposit_at, last_activity_at, updated_at FROM user_snapshots WHERE user_id = $1 FOR UPDATE
`

func (q *Queries) GetUserSnapshotForUpdate(ctx context.Context, userID uuid.UUID) (UserSnapshot, error) {
	row := q.db.QueryRow(ctx, getUserSnapshotForUpdate, userID)
	var i UserSnapshot
	err := row.Scan(
		&i.UserID,
		&i.ChipBalance,
		&i.TotalDeposited,
		&i.TotalReports,
		&i.LastDepositAt,
		&i.LastActivityAt,
		&i.UpdatedAt,
	)
	return i, err
}
