// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package pgstore

import (
	"context"

	uuid "github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, display_name, external_id, timezone, max_daily_deposit)
VALUES ($1, $2, NULLIF($3, ''), COALESCE(NULLIF($4, ''), 'UTC'), $5)
RETURNING id, display_name, external_id, timezone, max_daily_deposit, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	ID              uuid.UUID
	DisplayName     string
	Column3         interface{}
	Column4         interface{}
	MaxDailyDeposit int64
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.DisplayName,
		arg.Column3,
		arg.Column4,
		arg.MaxDailyDeposit,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.ExternalID,
		&i.Timezone,
		&i.MaxDailyDeposit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, display_name, external_id, timezone, max_daily_deposit, created_at, updated_at, deleted_at FROM users WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.ExternalID,
		&i.Timezone,
		&i.MaxDailyDeposit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByExternalID = `-- name: GetUserByExternalID :one
SELECT id, display_name, external_id, timezone, max_daily_deposit, created_at, updated_at, deleted_at FROM users WHERE external_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByExternalID(ctx context.Context, externalID *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByExternalID, externalID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.ExternalID,
		&i.Timezone,
		&i.MaxDailyDeposit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserSettings = `-- name: UpdateUserSettings :one
UPDATE users
SET
    display_name      = COALESCE(NULLIF($2, ''), display_name),
    timezone          = COALESCE(NULLIF($3, ''), timezone),
    max_daily_deposit = CASE WHEN $4::BIGINT < 0 THEN max_daily_deposit ELSE $4 END,
    updated_at        = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, display_name, external_id, timezone, max_daily_deposit, created_at, updated_at, deleted_at
`

type UpdateUserSettingsParams struct {
	ID      uuid.UUID
	Column2 interface{}
	Column3 interface{}
	Column4 int64
}

func (q *Queries) UpdateUserSettings(ctx context.Context, arg UpdateUserSettingsParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserSettings,
		arg.ID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.ExternalID,
		&i.Timezone,
		&i.MaxDailyDeposit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
